# Generated by Django 3.2.10 on 2024-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tasksCompleted',
            field=models.IntegerField(default=0),
        ),
    ]
